version: "3.8"

services:
  app:
    image: fuadgrimaldi/porto-backend:latest
    restart: unless-stopped
    container_name: porto-backend
    ports:
      - "127.0.0.1:4000:4000"
    networks:
      - portofolio
    volumes:
      - ./uploads:/app/public/uploads
    env_file:
      - ./src/server/.env
    mem_limit: 512m
    cpus: 1

  fe:
    image: fuadgrimaldi/porto-frontend:latest
    restart: unless-stopped
    container_name: porto-frontend
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - portofolio
    env_file:
      - ./src/my-porto/.env
    mem_limit: 512m
    cpus: 1

networks:
  portofolio:
    external: true
    name: personal-app_portofolio
