version: "3.8"

services:
  app:
    image: fuadgrimaldi/porto-backend:latest
    restart: unless-stopped
    container_name: porto-backend
    ports:
      - "4000:4000"
    networks:
      - portofolio
    volumes:
      - ./uploads:/app/public/uploads
    env_file:
      - /src/server/.env

  fe:
    image: fuadgrimaldi/porto-frontend:latest
    restart: unless-stopped
    container_name: porto-frontend
    ports:
      - "3000:3000"
    networks:
      - portofolio
    env_file:
      - /src/my-porto/.env

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_USER_ROOT}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - portofolio

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_USER_ROOT}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - portofolio

networks:
  portofolio:
