# app
# mysql
# phpmyadmin
# redis

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: fuadgrimaldi/server-porto:latest
    image: server-porto
    container_name: server-porto
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src/server:/var/www
    networks:
      - portofolio

  fe:
    image: fuadgrimaldi/client-porto:latest
    restart: unless-stopped
    container_name: client-porto
    ports:
      - "3000:3000"
    networks:
      - portofolio

networks:
  portofolio:
