# app
# mysql
# phpmyadmin
# redis

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: fuadgrimaldi/server-porto:latest
    image: server-porto
    container_name: server-porto
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src/server:/var/www
    networks:
      - portofolio

  fe:
    image: fuadgrimaldi/client-porto:latest
    restart: unless-stopped
    container_name: client-porto
    ports:
      - "3000:3000"
    networks:
      - portofolio

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${database_name}
      MYSQL_ROOT_PASSWORD: ${database_root_password}
      MYSQL_USER: ${database_user}
      MYSQL_PASSWORD: ${database_password}
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - portofolio

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${database_root_password}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - portofolio

networks:
  portofolio:
