import { Metadata } from "next";
import RootLayoutClient from "./rootLayoutClient";
import "../globals.css";

export const metadata: Metadata = {
  title: "Porfolio Fuad",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icon-head.png", // Path ke favicon/logo Anda
    shortcut: "/assets/icon-head.png", // (Opsional) Icon untuk shortcut
    apple: "/assets/icon-head.png", // (Opsional) Icon khusus perangkat Apple
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayoutClient>{children}</RootLayoutClient>;
}
