import React from "react";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Fuad",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icon-brand.png", // Gunakan path yang sama
    apple: "/assets/icon.png", // Gunakan path yang sama
    shortcut: "/assets/icon.png", // Gunakan path yang sama
  },
};
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="icon" href="/assets/icon-brand.png" type="image/png" />
        <link rel="apple-touch-icon" href="/assets/icon-brand.png" />
      </head>
      <body className="h-full">{children}</body>
    </html>
  );
}
