import React from "react";
import "./globals.css";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Fuad",
  description: "Generated by create next app",
};
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">{children}</body>
    </html>
  );
}
