import { Metadata } from "next";
import RootLayoutClient from "./rootLayoutClient";

export const metadata: Metadata = {
  title: "Porfolio Fuad",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icon-head.png", // Path ke favicon/logo Anda
    shortcut: "/assets/icon-head.png", // (Opsional) Icon untuk shortcut
    apple: "/assets/icon-head.png", // (Opsional) Icon khusus perangkat Apple
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
