name: Deploy FE to VPS via SSH

on:
  push:
    paths:
      - "src/my-porto/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker image
        working-directory: ./src/my-porto
        run: |
          docker build -t fuadgrimaldi/portofolio-frontend:latest .
          docker push fuadgrimaldi/portofolio-frontend:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔁 Ganti ke direktori project..."
            cd ~/httpdocs/personal-app

            echo "🛑 Stop container FE..."
            docker-compose stop fe || true
            docker-compose rm -f fe || true

            echo "🧼 Hapus image lama..."
            docker rmi fuadgrimaldi/portofolio-frontend:latest

            echo "📥 Pull image terbaru dari Docker Hub..."
            docker pull fuadgrimaldi/portofolio-frontend:latest

            echo "🚀 Jalankan container FE..."
            docker-compose up -d fe

            echo "Bersihkan image yang tidak terpakai..."
            docker image prune -af

            echo "✅ Reload nginx..."
            sudo nginx -t && sudo systemctl reload nginx
